# Generated by Django 3.2.21 on 2026-01-17 17:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('guide', '0002_booking_guide_transport'),
    ]

    operations = [
        migrations.AddField(
            model_name='guide',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='guide_profile', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='guide',
            name='bio',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='guide',
            name='daily_rate',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='guide',
            name='email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AlterField(
            model_name='guide',
            name='expertise',
            field=models.CharField(blank=True, help_text='e.g. History, Nature, Culture', max_length=200),
        ),
        migrations.AlterField(
            model_name='guide',
            name='languages',
            field=models.CharField(blank=True, help_text='Comma separated languages', max_length=200),
        ),
        migrations.AlterField(
            model_name='guide',
            name='phone',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
