# Generated by Django 3.2.21 on 2026-01-18 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guide', '0004_alter_booking_guide'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='itinerary_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
