# Generated by Django 3.2.21 on 2026-01-18 15:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('guide', '0008_communitymessage'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CommunityMessage',
        ),
    ]
