# Generated by Django 3.2.21 on 2026-01-18 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guide', '0009_delete_communitymessage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guide',
            name='daily_rate',
            field=models.DecimalField(decimal_places=2, default=800.0, max_digits=10),
        ),
    ]
