# Generated by Django 3.2.21 on 2026-01-21 19:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('guide', '0010_alter_guide_daily_rate'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='event',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='guide.event'),
        ),
        migrations.AddField(
            model_name='review',
            name='itinerary',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='guide.itinerary'),
        ),
        migrations.AlterField(
            model_name='review',
            name='location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='guide.location'),
        ),
    ]
